// Auto-generated by sigmoid_approximation.py on 2026-07-17 08:49:51
// DO NOT EDIT MANUALLY

#pragma once

#include "sigmoid_acceleration_profile.hh"
#include <array>

/**
 * @file sigmoid_acceleration_profile_100_1000_5_160mhz.hh
 * @brief Auto-generated Acceleration Profile
 * 
 * Profile Parameters:
 * - Speed Range: 100 -> 1000 steps/s
 * - Acceleration Time: 0.5 seconds
 * - Timer Input Frequency: 160.0 MHz
 * - Prescaler: 24 (Timer Frequency: 6400000.00 Hz)
 * - Shift Bits: 10
 * - Segments: 48
 * - Total Steps (Accel + Decel): 548
 */

// Lookup table with 48 segments
constexpr std::array<AccelerationSegment, 48> segments_profile_100_1000_5_160mhz = {{
    {1, -394240},
    {1, -490496},
    {1, -605184},
    {1, -740352},
    {1, -899072},
    {1, -1076224},
    {1, -1270784},
    {1, -1475584},
    {1, -1683456},
    {1, -1882112},
    {1, -2058240},
    {1, -2201600},
    {2, -2333696},
    {2, -2347008},
    {1, -2260992},
    {1, -2162688},
    {1, -2044928},
    {1, -1916928},
    {1, -1784832},
    {1, -1651712},
    {1, -1523712},
    {1, -1401856},
    {1, -1288192},
    {1, -1182720},
    {1, -1085440},
    {1, -997376},
    {1, -916480},
    {1, -843776},
    {1, -777216},
    {2, -688640},
    {2, -590848},
    {2, -509440},
    {2, -442368},
    {3, -372394},
    {3, -308566},
    {3, -258048},
    {4, -211456},
    {5, -167526},
    {5, -132096},
    {7, -101083},
    {8, -74880},
    {10, -53658},
    {13, -36549},
    {17, -23190},
    {25, -12861},
    {39, -5724},
    {85, -1421},
    {8, -520}

}};


// Profile instance for easy access
constexpr SigmoidAccelerationProfile profile_100_1000_5_160mhz(
    6400000,  // timer_freq_hz
    24,        // prescaler
    63999,      // initial_arr
    100,   // start_speed_steps_per_s
    1000,  // target_speed_steps_per_s
    10,       // shift_bits
    548, // total_steps (accel + decel)
    segments_profile_100_1000_5_160mhz
);
