// Auto-generated by sigmoid_approximation.py on 2026-02-17 22:49:25
// DO NOT EDIT MANUALLY

#pragma once

#include "sigmoid_acceleration_profile.hh"
#include <array>

/**
 * @file sigmoid_acceleration_profile_100_1000_5_170mhz.hh
 * @brief Auto-generated Acceleration Profile
 * 
 * Profile Parameters:
 * - Speed Range: 100 -> 1000 steps/s
 * - Acceleration Time: 0.5 seconds
 * - Timer Input Frequency: 170.0 MHz
 * - Prescaler: 25 (Timer Frequency: 6538461.54 Hz)
 * - Shift Bits: 10
 * - Segments: 48
 * - Total Steps (Accel + Decel): 548
 */

// Lookup table with 48 segments
constexpr std::array<AccelerationSegment, 48> segments_profile_100_1000_5_170mhz = {{
    {1, -402432},
    {1, -500736},
    {1, -617472},
    {1, -757760},
    {1, -917504},
    {1, -1099776},
    {1, -1298432},
    {1, -1508352},
    {1, -1719296},
    {1, -1922048},
    {1, -2103296},
    {1, -2249728},
    {1, -2353152},
    {3, -2406742},
    {1, -2300926},
    {1, -2209792},
    {1, -2089984},
    {1, -1957888},
    {1, -1822720},
    {1, -1687552},
    {1, -1556480},
    {1, -1432576},
    {1, -1315840},
    {1, -1208320},
    {1, -1108992},
    {1, -1018880},
    {1, -935936},
    {1, -862208},
    {1, -793600},
    {2, -703488},
    {2, -603648},
    {2, -520704},
    {2, -451584},
    {3, -380586},
    {3, -315392},
    {3, -263510},
    {4, -216064},
    {5, -171008},
    {5, -134963},
    {6, -105642},
    {8, -79232},
    {10, -56832},
    {12, -39253},
    {16, -25408},
    {23, -14648},
    {35, -6933},
    {69, -2078},
    {33, -558}

}};


// Profile instance for easy access
constexpr SigmoidAccelerationProfile profile_100_1000_5_170mhz(
    6538461,  // timer_freq_hz
    25,        // prescaler
    65383,      // initial_arr
    100,   // start_speed_steps_per_s
    1000,  // target_speed_steps_per_s
    10,       // shift_bits
    548, // total_steps (accel + decel)
    segments_profile_100_1000_5_170mhz
);
